version: 2

models:
  - name: bronze_bookings
    description: "Bronze layer model for bookings data"

  - name: bronze_hosts
    description: "Bronze layer model for hosts data"

  - name: bronze_listings
    description: "Bronze layer model for listings data"